# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon        = "img/favicon.png"

# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy              = "default"

[footer]
    since      = 2025
    customText = "ProsD | Human curated, AI assisted."

[dateFormat]
    published   = ":date_full"
    lastUpdated = ":date_full"

[sidebar]
    emoji    = "x"
    subtitle = "A public dumping ground for my obsession with Local LLMs, abandonware, and voiding warranties."
    avatar   = "img/avatar.png"

[article]
    headingAnchor = true
    math          = true
    readingTime   = true

    [article.license]
        enabled = true
        default = "CC BY-NC-SA 4.0 â€¢ Human curated, AI assisted."

[widgets]
    homepage = [
        { type = "search" },
        { type = "categories", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[colorScheme]
    toggle  = false
    default = "dark"

## Comments
[comments]
    enabled  = false
    provider = "disqus"

    # See all the available configurations at https://github.com/CaiJimmy/hugo-theme-stack/blob/master/config/_default/params.toml
    # Copy the configurations you need from there and paste it here.
